included:
  - LeetCode
  - Structure
  - Tests
excluded:
  - LeetCode/*/RandomPointinNonoverlappingRectangles.swift

disabled_rules:
  - nesting
  - identifier_name
  - type_name
  - large_tuple
opt_in_rules:
  - yoda_condition

line_length:
  warning: 120
  error: 240
