name: LeetCode

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install xcode-install
      run: gem install xcode-install
    - name: Build and Tests
      run: swift test --enable-code-coverage
    - name: Export codecov profdata
      run: xcrun llvm-cov export -format="lcov" .build/debug/LeetCodePackageTests.xctest/Contents/MacOS/LeetCodePackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload
      run: bash <(curl https://codecov.io/bash)
